spring:
  application:
    name: catalog-service-parcial
  config:
    import: configserver:http://localhost:8888

resilience4j:
  circuitbreaker:
    instances:
      movies:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 2
        sliding-window-type: COUNT_BASED
        sliding-window-size: 2
      series:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 2
        sliding-window-type: COUNT_BASED
        sliding-window-size: 2
  retry:
    retry-aspect-order: 2
    instances:
      movies:
        max-attempts: 2
        wait-duration: 10s
        retry-exceptions:
          - feign.FeignException$InternalServerError
      series:
        max-attempts: 2
        wait-duration: 10s
        retry-exceptions:
          - feign.FeignException$InternalServerError
management:
  health:
    circuitbreakers:
      enabled: 'true'
  endpoint:
    health:
      show-details: always



