server:
  port: '${PORT:${SERVER_PORT:8080}}'
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: catalog-service-parcial
          uri: lb://catalog-service-parcial
          predicates:
            - Path=/catalog/**
        - id: movie-service-parcial
          uri: lb://movie-service-parcial
          predicates:
            - Path=/movies/**
        - id: serie-service-parcial
          uri: lb://serie-service-parcial
          predicates:
            - Path=/series/**

  zipkin:
    base-url: 'http://localhost:9411/'
    enabled: true
info:
  app:
    name: '${spring.application.name}'
eureka:
  instance:
    instance-id: '${spring.application.name}:${random.uuid}'
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceURL:
      defaultZone: 'http://localhost:8761/eureka'
  management:
    endpoint:
      gateway:
        enabled: true
    endpoints:
      web:
        exposure:
          include: gateway
  health:
    circuitbreakers:
      enabled: 'true'
  endpoint:
    health:
      show-details: always
