server:
  port: '${PORT:${SERVER_PORT:0}}'
spring:
  application:
    name: catalog-service-parcial
  zipkin:
    base-url: 'http://localhost:9411/'
    enabled: true
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: test
      port: 27017
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
queue:
  serie:
    name: NewSerie
  movie:
    name: NewMovie
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: 'true'
  endpoint:
    health:
      show-details: always
eureka:
  instance:
    instance-id: '${spring.application.name}:${random.uuid}'
resilience4j:
  circuitbreaker:
    instances:
      movies:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 2
        sliding-window-type: COUNT_BASED
        sliding-window-size: 2
      series:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 2
        sliding-window-type: COUNT_BASED
        sliding-window-size: 2
  retry:
    retry-aspect-order: 2
    instances:
      movies:
        max-attempts: 2
        wait-duration: 10s
        retry-exceptions:
          - feign.FeignException$InternalServerError
      series:
        max-attempts: 2
        wait-duration: 10s
        retry-exceptions:
          - feign.FeignException$InternalServerError
